domain_path: /home3/shared/chapman44/cheshire/platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home3/CAD/Vitis2025_2/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
